import Head from "next/head";
import styles from "@/styles/Home.module.css";
import HomeElement from "./components/home";
import Navbar from "./components/navbar";
import AboutElement from "./components/about";
import Activities from "./components/activities";
export default function Home() {
    return (
        <>
            <Head>
                <title>Justin Maximillian Kimlim</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Navbar />
                <HomeElement />
                <AboutElement />
                <Activities />
            </main>
        </>
    );
}
