import Image from 'next/image';
import { METRICS_SRC } from '../../Util/constant';
const AboutMe = () => {
    return (
        <>
            <h2 className="about-heading" id="about">
                About me
            </h2>
            <div className="about">
                <div className="about-metrics">
                    <Image
                        loader={() => METRICS_SRC}
                        src={METRICS_SRC}
                        width="100%"
                        height="100%"
                        layout="responsive"
                        objectFit="contain"
                        alt="Justin Maximillian Kimlim's metric"
                    />
                </div>
                <div className="about-description">
                    <p>
                        Hola 👋, I{"'"}m <strong>Justin Maximillian Kimlim</strong>, or known as <strong>kimlimjustin</strong> for short which I used
                        as username on platforms like{' '}
                        <a href="https://github.com/kimlimjustin" target="_blank" rel="noreferrer">
                            GitHub
                        </a>
                        ,{' '}
                        <a href="https://twitter.com/kimlimjustin" target="_blank" rel="noreferrer">
                            Twitter
                        </a>
                        , and others. I{"'"}m currently a high school student at a high school in Indonesia.
                    </p>
                    <p>
                        Covid 19 has changed everyone{"'"}s life, or at least me. As a result of being bored after months of lockdown, I started to
                        try something new and fell in love with programming inadvertently.
                    </p>
                    <p>
                        I gained experience by actively building projects such as{' '}
                        <a href="https://github.com/kimlimjustin/xplorer" target="_blank" rel="noreferrer">
                            Xplorer
                        </a>{' '}
                        and others which can be found on{' '}
                        <a href="https://github.com/kimlimjustin?tab=repositories" target="_blank" rel="noreferrer">
                            GitHub
                        </a>{' '}
                        for more than one year and achieved some achievements as shown beside. (Metrics generated by{' '}
                        <a href="https://metrics.lecoq.io/" target="_blank" rel="noreferrer">
                            Metrics
                        </a>
                        )
                    </p>
                    <p>
                        I can{"'"}t list all things that I{"'"}m familiar with here, but here are several: ReactJS, NextJS, JavaScript (TypeScript),
                        Rust, Python. I{"'"} also a multilingual person who speaks English, Indonesian, Chinese, and Japanese.
                    </p>
                    <p>
                        Any questions or just want to say hi? Don{"'"}t hesitate to <a href="mailto:kimlimjustin@gmail.com">say hi!</a>
                    </p>
                </div>
            </div>
        </>
    );
};
export default AboutMe;
